--   1) snapshot-like через временную таблицу;
--   2) workset с WHERE CURRENT OF;
--   3) обычный курсор по текущему состоянию выборки.

drop procedure if exists pr_cursor_iso_conference_stats();
drop procedure if exists pr_cursor_snapshot_like();
drop procedure if exists pr_cursor_update_scholarship_where_current_of(text, numeric);
drop procedure if exists pr_cursor_delete_inactive_where_current_of(text);

drop table if exists tmp_cursor_conf_stats;
drop table if exists tmp_cursor_snapshot;
drop table if exists tmp_cursor_workset;
drop table if exists tmp_cursor_action_log;


-- ============================================================
-- 1) курсор и пошаговая обработка строк
-- ============================================================

create or replace procedure pr_cursor_iso_conference_stats()
language plpgsql
as $$
declare
  cur_conf cursor for
    select
      k."ID_конференции",
      k."Название"
    from "Конференция" k
    order by k."Название";

  v_id_conf integer;
  v_conf_name varchar(200);
  v_cnt bigint;
begin
  drop table if exists tmp_cursor_conf_stats;

  create temp table tmp_cursor_conf_stats (
    id_konferencii integer not null,
    nazvanie_konferencii varchar(200) not null,
    kolichestvo_uchastiy bigint not null
  ) on commit preserve rows;

  open cur_conf;

  loop
    fetch cur_conf into v_id_conf, v_conf_name;
    exit when not found;

    select count(*)::bigint
    into v_cnt
    from "Выступление_студент" vs
    join "Выступление" v on v."ID_выступления" = vs."ID_выступления"
    join "Программа_конференции" pc on pc."ID_программы" = v."ID_программы"
    where pc."ID_конференции" = v_id_conf;

    insert into tmp_cursor_conf_stats (id_konferencii, nazvanie_konferencii, kolichestvo_uchastiy)
    values (v_id_conf, v_conf_name, coalesce(v_cnt, 0));
  end loop;

  close cur_conf;
end;
$$;


-- ============================================================
-- 2) "Snapshot-like" (аналог static)
-- ============================================================

create or replace procedure pr_cursor_snapshot_like()
language plpgsql
as $$
declare
  cur_snap cursor for
    select fio, nomer_gruppy, kol_uchastiy
    from tmp_cursor_snapshot
    order by fio;

  v_fio varchar(150);
  v_group varchar(20);
  v_cnt bigint;
begin
  drop table if exists tmp_cursor_snapshot;
  drop table if exists tmp_cursor_action_log;

  create temp table tmp_cursor_snapshot (
    fio varchar(150) not null,
    nomer_gruppy varchar(20) not null,
    kol_uchastiy bigint not null
  ) on commit preserve rows;

  create temp table tmp_cursor_action_log (
    step_no integer generated by default as identity primary key,
    action_text text not null,
    action_time timestamp not null default now()
  ) on commit preserve rows;

  insert into tmp_cursor_snapshot (fio, nomer_gruppy, kol_uchastiy)
  select
    s."ФИО",
    g."Номер_группы",
    count(vs."ID_выступления")::bigint as kol_uchastiy
  from "Студент" s
  join "Группа" g on g."ID_группы" = s."ID_группы"
  left join "Выступление_студент" vs on vs."ID_студента" = s."ID_студента"
  group by s."ID_студента", s."ФИО", g."Номер_группы";

  open cur_snap;

  -- Во время чтения курсора имитируем параллельное изменение базы.
  update "Студент"
  set "ФИО" = "ФИО"
  where "ID_студента" in (
    select s2."ID_студента" from "Студент" s2 order by s2."ID_студента" limit 1
  );

  insert into tmp_cursor_action_log (action_text)
  values ('Выполнено изменение в базовой таблице после открытия курсора snapshot-like.');

  loop
    fetch cur_snap into v_fio, v_group, v_cnt;
    exit when not found;

    insert into tmp_cursor_action_log (action_text)
    values (format('Снимок: %s | группа %s | участий %s', v_fio, v_group, v_cnt));
  end loop;

  close cur_snap;
end;
$$;


-- ============================================================
-- 3) UPDATE ... WHERE CURRENT OF
-- ============================================================

create or replace procedure pr_cursor_update_scholarship_where_current_of(
  p_group text,
  p_percent numeric default 10
)
language plpgsql
as $$
declare
  cur_upd cursor for
    select
      s."ID_студента",
      s."ФИО",
      s."Стипендия"
    from tmp_cursor_workset s
    where s."Номер_группы" = p_group
    for update;

  r record;
begin
  if p_percent <= 0 then
    raise exception 'Процент повышения должен быть положительным';
  end if;

  drop table if exists tmp_cursor_workset;

  create temp table tmp_cursor_workset (
    "ID_студента" integer primary key,
    "ФИО" varchar(150) not null,
    "Номер_группы" varchar(20) not null,
    "Стипендия" numeric(12,2) not null
  ) on commit preserve rows;

  insert into tmp_cursor_workset ("ID_студента", "ФИО", "Номер_группы", "Стипендия")
  select
    s."ID_студента",
    s."ФИО",
    g."Номер_группы",
    1000::numeric(12,2) as "Стипендия"
  from "Студент" s
  join "Группа" g on g."ID_группы" = s."ID_группы";

  open cur_upd;

  loop
    fetch cur_upd into r;
    exit when not found;

    update tmp_cursor_workset
    set "Стипендия" = round("Стипендия" * (1 + p_percent / 100.0), 2)
    where current of cur_upd;
  end loop;

  close cur_upd;
end;
$$;


-- ============================================================
-- 4) DELETE ... WHERE CURRENT OF
-- ============================================================

create or replace procedure pr_cursor_delete_inactive_where_current_of(
  p_conference text default 'Информатика'
)
language plpgsql
as $$
declare
  cur_del cursor for
    select
      s."ID_студента",
      s."ФИО"
    from "Студент" s
    for update;

  r record;
begin
  open cur_del;

  loop
    fetch cur_del into r;
    exit when not found;

    if not exists (
      select 1
      from "Выступление_студент" vs
      join "Выступление" v on v."ID_выступления" = vs."ID_выступления"
      join "Программа_конференции" pc on pc."ID_программы" = v."ID_программы"
      join "Конференция" k on k."ID_конференции" = pc."ID_конференции"
      where vs."ID_студента" = r."ID_студента"
        and k."Название" = p_conference
    ) then
      delete from "Студент"
      where current of cur_del;
    end if;
  end loop;

  close cur_del;
end;
$$;

