DROP TABLE IF EXISTS "Выступление_студент" CASCADE;
DROP TABLE IF EXISTS "Выступление" CASCADE;
DROP TABLE IF EXISTS "Программа_конференции" CASCADE;
DROP TABLE IF EXISTS "Конференция" CASCADE;
DROP TABLE IF EXISTS "Студент" CASCADE;
DROP TABLE IF EXISTS "Группа" CASCADE;
DROP TABLE IF EXISTS "Факультет" CASCADE;
DROP TABLE IF EXISTS "Вуз" CASCADE;

CREATE TABLE "Вуз" (
  "ID_вуза" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Название" VARCHAR(200) NOT NULL UNIQUE CHECK (char_length(trim(both FROM "Название")) > 0)
);

CREATE TABLE "Факультет" (
  "ID_факультета" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ID_вуза" INTEGER NOT NULL,
  "Номер_факультета" SMALLINT NOT NULL CHECK ("Номер_факультета" > 0),
  "Название" VARCHAR(200),
  UNIQUE ("ID_вуза", "Номер_факультета"),

  -- Факультет принадлежит одному вузу
  CONSTRAINT fk_fakultet_vuz
    FOREIGN KEY ("ID_вуза")
    REFERENCES "Вуз" ("ID_вуза")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE "Группа" (
  "ID_группы" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ID_факультета" INTEGER NOT NULL,
  "Номер_группы" VARCHAR(20) NOT NULL CHECK (char_length(trim(both FROM "Номер_группы")) > 0),
  UNIQUE ("ID_факультета", "Номер_группы"),

  -- Группа закреплена за факультетом
  CONSTRAINT fk_grupa_fakultet
    FOREIGN KEY ("ID_факультета")
    REFERENCES "Факультет" ("ID_факультета")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE "Студент" (
  "ID_студента" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ID_группы" INTEGER NOT NULL,
  "ФИО" VARCHAR(150) NOT NULL CHECK (char_length(trim(both FROM "ФИО")) > 0),

  -- Студент учится в одной группе
  CONSTRAINT fk_student_grupa
    FOREIGN KEY ("ID_группы")
    REFERENCES "Группа" ("ID_группы")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE "Конференция" (
  "ID_конференции" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Название" VARCHAR(200) NOT NULL UNIQUE CHECK (char_length(trim(both FROM "Название")) > 0)
);

CREATE TABLE "Программа_конференции" (
  "ID_программы" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ID_конференции" INTEGER NOT NULL UNIQUE,

  -- Одна программа на одну конференцию
  CONSTRAINT fk_programma_konferenciya
    FOREIGN KEY ("ID_конференции")
    REFERENCES "Конференция" ("ID_конференции")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE "Выступление" (
  "ID_выступления" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ID_программы" INTEGER NOT NULL,
  "Название_темы" VARCHAR(300) NOT NULL CHECK (char_length(trim(both FROM "Название_темы")) > 0),

  -- Доклад входит в программу конференции
  CONSTRAINT fk_vystuplenie_programma
    FOREIGN KEY ("ID_программы")
    REFERENCES "Программа_конференции" ("ID_программы")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE "Выступление_студент" (
  "ID_выступления" INTEGER NOT NULL,
  "ID_студента" INTEGER NOT NULL,
  PRIMARY KEY ("ID_выступления", "ID_студента"),

  -- Участие в конкретном выступлении
  CONSTRAINT fk_vs_vystuplenie
    FOREIGN KEY ("ID_выступления")
    REFERENCES "Выступление" ("ID_выступления")
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_vs_student
    FOREIGN KEY ("ID_студента")
    REFERENCES "Студент" ("ID_студента")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
