-- ЛР7, вариант 5 (PostgreSQL)
-- Триггеры: after и instead of для insert/update/delete + триггер статистики.

-- ============================================================
-- 0) Служебные объекты
-- ============================================================

drop trigger if exists trg_student_after_insert on "Студент";
drop trigger if exists trg_student_after_update on "Студент";
drop trigger if exists trg_student_after_delete on "Студент";
drop trigger if exists trg_vs_stats_after_ins_upd_del on "Выступление_студент";

drop function if exists fn_student_after_insert();
drop function if exists fn_student_after_update();
drop function if exists fn_student_after_delete();
drop function if exists fn_vs_stats_after_ins_upd_del();

drop function if exists fn_v_student_editor_ins();
drop function if exists fn_v_student_editor_upd();
drop function if exists fn_v_student_editor_del();

drop view if exists v_student_editor;
drop table if exists "Журнал_изменений_студент";
drop table if exists "Статистика_участий_по_конференции";

create table "Журнал_изменений_студент" (
  "ID_записи" integer generated by default as identity primary key,
  "Операция" varchar(20) not null,
  "ID_студента" integer,
  "Старое_ФИО" varchar(150),
  "Новое_ФИО" varchar(150),
  "Старый_ID_группы" integer,
  "Новый_ID_группы" integer,
  "Дата_операции" timestamp not null default now()
);

create table "Статистика_участий_по_конференции" (
  "ID_конференции" integer primary key,
  "Название_конференции" varchar(200) not null,
  "Количество_участий" integer not null default 0,
  "Дата_обновления" timestamp not null default now()
);


-- ============================================================
-- 1) AFTER-триггеры на таблицу "Студент"
-- ============================================================

-- AFTER INSERT: контроль максимальной численности группы + запись в журнал.
create or replace function fn_student_after_insert()
returns trigger
language plpgsql
as $$
declare
  v_cnt integer;
begin
  select count(*)
  into v_cnt
  from "Студент" s
  where s."ID_группы" = new."ID_группы";

  if v_cnt > 20 then
    raise exception 'В группе ID=% превышен лимит 20 студентов (сейчас %)', new."ID_группы", v_cnt;
  end if;

  insert into "Журнал_изменений_студент" (
    "Операция", "ID_студента", "Новое_ФИО", "Новый_ID_группы"
  )
  values (
    'AFTER INSERT', new."ID_студента", new."ФИО", new."ID_группы"
  );

  return new;
end;
$$;

create trigger trg_student_after_insert
after insert on "Студент"
for each row
execute function fn_student_after_insert();


-- AFTER UPDATE: контроль численности при переводе + запись в журнал.
create or replace function fn_student_after_update()
returns trigger
language plpgsql
as $$
declare
  v_cnt integer;
begin
  if new."ID_группы" is distinct from old."ID_группы" then
    select count(*)
    into v_cnt
    from "Студент" s
    where s."ID_группы" = new."ID_группы";

    if v_cnt > 20 then
      raise exception 'После перевода в группе ID=% превышен лимит 20 студентов (сейчас %)', new."ID_группы", v_cnt;
    end if;
  end if;

  insert into "Журнал_изменений_студент" (
    "Операция", "ID_студента", "Старое_ФИО", "Новое_ФИО", "Старый_ID_группы", "Новый_ID_группы"
  )
  values (
    'AFTER UPDATE',
    new."ID_студента",
    old."ФИО",
    new."ФИО",
    old."ID_группы",
    new."ID_группы"
  );

  return new;
end;
$$;

create trigger trg_student_after_update
after update on "Студент"
for each row
execute function fn_student_after_update();


-- AFTER DELETE: удаление пустой группы + запись в журнал.
create or replace function fn_student_after_delete()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from "Студент" s
    where s."ID_группы" = old."ID_группы"
  ) then
    delete from "Группа" g
    where g."ID_группы" = old."ID_группы";
  end if;

  insert into "Журнал_изменений_студент" (
    "Операция", "ID_студента", "Старое_ФИО", "Старый_ID_группы"
  )
  values (
    'AFTER DELETE', old."ID_студента", old."ФИО", old."ID_группы"
  );

  return old;
end;
$$;

create trigger trg_student_after_delete
after delete on "Студент"
for each row
execute function fn_student_after_delete();


-- ============================================================
-- 2) INSTEAD OF-триггеры на представление
-- ============================================================

create or replace view v_student_editor as
select
  s."ID_студента",
  s."ФИО",
  g."Номер_группы",
  f."Номер_факультета",
  vz."Название" as "Вуз"
from "Студент" s
join "Группа" g on g."ID_группы" = s."ID_группы"
join "Факультет" f on f."ID_факультета" = g."ID_факультета"
join "Вуз" vz on vz."ID_вуза" = f."ID_вуза";


create or replace function fn_v_student_editor_ins()
returns trigger
language plpgsql
as $$
declare
  v_id_fakulteta integer;
  v_id_grupy integer;
begin
  select f."ID_факультета"
  into v_id_fakulteta
  from "Факультет" f
  join "Вуз" vz on vz."ID_вуза" = f."ID_вуза"
  where f."Номер_факультета" = new."Номер_факультета"
    and vz."Название" = new."Вуз";

  if v_id_fakulteta is null then
    raise exception 'Не найден факультет №% в вузе %', new."Номер_факультета", new."Вуз";
  end if;

  select g."ID_группы"
  into v_id_grupy
  from "Группа" g
  where g."ID_факультета" = v_id_fakulteta
    and g."Номер_группы" = new."Номер_группы";

  if v_id_grupy is null then
    insert into "Группа" ("ID_факультета", "Номер_группы")
    values (v_id_fakulteta, new."Номер_группы")
    returning "ID_группы" into v_id_grupy;
  end if;

  insert into "Студент" ("ID_группы", "ФИО")
  values (v_id_grupy, new."ФИО")
  returning "ID_студента" into new."ID_студента";

  return new;
end;
$$;

create trigger trg_v_student_editor_ins
instead of insert on v_student_editor
for each row
execute function fn_v_student_editor_ins();


create or replace function fn_v_student_editor_upd()
returns trigger
language plpgsql
as $$
declare
  v_id_fakulteta integer;
  v_id_grupy integer;
begin
  select f."ID_факультета"
  into v_id_fakulteta
  from "Факультет" f
  join "Вуз" vz on vz."ID_вуза" = f."ID_вуза"
  where f."Номер_факультета" = new."Номер_факультета"
    and vz."Название" = new."Вуз";

  if v_id_fakulteta is null then
    raise exception 'Не найден факультет №% в вузе %', new."Номер_факультета", new."Вуз";
  end if;

  select g."ID_группы"
  into v_id_grupy
  from "Группа" g
  where g."ID_факультета" = v_id_fakulteta
    and g."Номер_группы" = new."Номер_группы";

  if v_id_grupy is null then
    insert into "Группа" ("ID_факультета", "Номер_группы")
    values (v_id_fakulteta, new."Номер_группы")
    returning "ID_группы" into v_id_grupy;
  end if;

  update "Студент"
  set
    "ФИО" = new."ФИО",
    "ID_группы" = v_id_grupy
  where "ID_студента" = old."ID_студента";

  return new;
end;
$$;

create trigger trg_v_student_editor_upd
instead of update on v_student_editor
for each row
execute function fn_v_student_editor_upd();


create or replace function fn_v_student_editor_del()
returns trigger
language plpgsql
as $$
begin
  delete from "Студент"
  where "ID_студента" = old."ID_студента";

  return old;
end;
$$;

create trigger trg_v_student_editor_del
instead of delete on v_student_editor
for each row
execute function fn_v_student_editor_del();


-- ============================================================
-- 3) AFTER-триггер статистики (insert/update/delete)
-- ============================================================

create or replace function fn_vs_stats_after_ins_upd_del()
returns trigger
language plpgsql
as $$
declare
  v_id_conf_old integer;
  v_id_conf_new integer;
begin
  if tg_op in ('DELETE', 'UPDATE') then
    select pc."ID_конференции"
    into v_id_conf_old
    from "Выступление" v
    join "Программа_конференции" pc on pc."ID_программы" = v."ID_программы"
    where v."ID_выступления" = old."ID_выступления";

    if v_id_conf_old is not null then
      insert into "Статистика_участий_по_конференции" (
        "ID_конференции", "Название_конференции", "Количество_участий", "Дата_обновления"
      )
      select
        k."ID_конференции", k."Название", 0, now()
      from "Конференция" k
      where k."ID_конференции" = v_id_conf_old
      on conflict ("ID_конференции") do nothing;

      update "Статистика_участий_по_конференции"
      set
        "Количество_участий" = greatest(0, "Количество_участий" - 1),
        "Дата_обновления" = now()
      where "ID_конференции" = v_id_conf_old;
    end if;
  end if;

  if tg_op in ('INSERT', 'UPDATE') then
    select pc."ID_конференции"
    into v_id_conf_new
    from "Выступление" v
    join "Программа_конференции" pc on pc."ID_программы" = v."ID_программы"
    where v."ID_выступления" = new."ID_выступления";

    if v_id_conf_new is not null then
      insert into "Статистика_участий_по_конференции" (
        "ID_конференции", "Название_конференции", "Количество_участий", "Дата_обновления"
      )
      select
        k."ID_конференции", k."Название", 0, now()
      from "Конференция" k
      where k."ID_конференции" = v_id_conf_new
      on conflict ("ID_конференции") do nothing;

      update "Статистика_участий_по_конференции"
      set
        "Количество_участий" = "Количество_участий" + 1,
        "Дата_обновления" = now()
      where "ID_конференции" = v_id_conf_new;
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create trigger trg_vs_stats_after_ins_upd_del
after insert or update or delete on "Выступление_студент"
for each row
execute function fn_vs_stats_after_ins_upd_del();


-- Инициализация статистики по текущим данным.
insert into "Статистика_участий_по_конференции" (
  "ID_конференции", "Название_конференции", "Количество_участий", "Дата_обновления"
)
select
  k."ID_конференции",
  k."Название",
  count(vs."ID_студента")::integer as "Количество_участий",
  now()
from "Конференция" k
left join "Программа_конференции" pc on pc."ID_конференции" = k."ID_конференции"
left join "Выступление" v on v."ID_программы" = pc."ID_программы"
left join "Выступление_студент" vs on vs."ID_выступления" = v."ID_выступления"
group by k."ID_конференции", k."Название"
on conflict ("ID_конференции") do update
set
  "Название_конференции" = excluded."Название_конференции",
  "Количество_участий" = excluded."Количество_участий",
  "Дата_обновления" = now();


-- ============================================================
-- 4) Демонстрационные вызовы (для скриншотов в отчёт)
-- ============================================================

-- INSTEAD OF INSERT (через представление)
-- insert into v_student_editor ("ФИО", "Номер_группы", "Номер_факультета", "Вуз")
-- values ('Тест ЛР7 Представление INSERT', '4999', 4, 'ГУАП');

-- INSTEAD OF UPDATE (через представление)
-- update v_student_editor
-- set "Номер_группы" = '4550'
-- where "ФИО" = 'Тест ЛР7 Представление INSERT';

-- INSTEAD OF DELETE (через представление)
-- delete from v_student_editor
-- where "ФИО" = 'Тест ЛР7 Представление INSERT';

-- AFTER INSERT / UPDATE / DELETE (через базовую таблицу)
-- insert into "Студент" ("ID_группы", "ФИО")
-- select "ID_группы", 'Тест ЛР7 AFTER'
-- from "Группа"
-- where "Номер_группы" = '4226'
-- order by "ID_группы"
-- limit 1;

-- update "Студент"
-- set "ФИО" = 'Тест ЛР7 AFTER (обновлён)'
-- where "ФИО" = 'Тест ЛР7 AFTER';

-- delete from "Студент"
-- where "ФИО" = 'Тест ЛР7 AFTER (обновлён)';

-- Демонстрация статистического триггера
-- insert into "Выступление_студент" ("ID_выступления", "ID_студента")
-- select v."ID_выступления", s."ID_студента"
-- from "Выступление" v
-- join "Программа_конференции" pc on pc."ID_программы" = v."ID_программы"
-- join "Конференция" k on k."ID_конференции" = pc."ID_конференции"
-- join "Студент" s on s."ФИО" = 'Алексеев Иван Сергеевич'
-- where k."Название" = 'Энергетика и экология'
-- order by v."ID_выступления"
-- limit 1
-- on conflict do nothing;

select *
from "Журнал_изменений_студент"
order by "ID_записи" desc
limit 20;

select *
from "Статистика_участий_по_конференции"
order by "ID_конференции";
